# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a4d436847f90d1993804ee5167c9b2721a79fd22033ee96f2bced57066fdfb091747431db639cf22298dc2c60f8800ae5f685cd0a37250eaa99835770b565fc

test:
  secret_key_base: cf7a925cbaf0bf4ecdacfb5988387844b7f7d570083dffc7ef29c242bd6191d3c2c4af10800ccd35b84db3aa28ae4c9dc591ed64065b591d51e1686518aed053

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
